spring:
  application:
    name: google-login
  data:
    mongodb:
      url: mongodb://localhost:27017/
      database: googleDb
server:
  port: 8086
  error:
    include-message: always
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka

